### ISSUE TITLE
Using Batch Files to Convert

### ISSUE THREAD

**Issue by m1developer** [cristoper/wav2vec#1]
I was playing around with your API -- which is a fantastic little tool -- and I came across an issue where  converting a .wav to .svg using a batch script fails to create a usable .svg.  I've attached the batch script I'm using (in .txt format).  As a side note, this does create an .svg file, it just does not have usable data.  Any insight into this issue would be great.  Thanks in advance.

[wavTosvg.txt](https://github.com/cristoper/wav2vec/files/3871915/wavTosvg.txt)

**Comment by cristoper** [comment]
I notice that your script is calling the program as "wave2vec" (with an extra 'e') instead of "wav2vec". Could that be the problem (it is creating an empty .svg file because it can't find the command)?

Otherwise, if you can send me a .wav file that causes the problem I will try to reproduce it.

Thanks!

**Comment by m1developer** [comment]
Yeap...that wave2vec instead of wav2vec was the issue.  Thanks for looking into that -- I had a feeling it was something silly.  Appreciate the swift response, and again, thanks for this fantastic little tool.  This will make my life a thousand times easier.

**Comment by m1developer** [comment]
Final caveat, I did have to change the batch script slightly.  Instead of: 
start cmd.exe /c wav2Vec...
I needed to use:
CMD /c wav2vec...
Not sure why this made a difference...but when you use the method that doesn't work, the wav data is printed to the command console window instead of into the output file.

**Comment by cristoper** [comment]
Thanks for the followup. I've never actually tried running wav2vec under Windows before, so I'm glad you were able to get it working!
